<?php
return [
 'meta_title'=>'Reparația MFD, multifuncționalelor și copiatoarelor în Chișinău','meta_description'=>'Diagnosticare, reparație și întreținere pentru MFD, imprimante multifuncționale și copiatoare în Chișinău.','meta_keywords'=>'reparație MFD Chișinău, reparație copiatoare, service multifuncționale, reparație xerox','seo_location'=>'în Chișinău',
 'home'=>'Acasă','print_services'=>'Servicii imprimante','repairs'=>'Reparația MFD și Copiatoarelor','eyebrow'=>'Service echipamente de birou în Chișinău','hero_title'=>'Reparația MFD și Copiatoarelor','hero_text'=>'Diagnosticăm și reparăm multifuncționale, copiatoare și echipamente de birou laser. Verificăm aparatul și confirmăm soluția, termenul și costul înainte de intervenție.','hero_alt'=>'Reparația unui copiator multifuncțional în service','call'=>'Sună: 060 229 129','see_services'=>'Vezi serviciile',
 'services_eyebrow'=>'Diagnosticare, mecanică și electronică','services_title'=>'Servicii pentru MFD și copiatoare','services_text'=>'Selectează problema pentru a vedea simptomele frecvente și etapele reparației.','details'=>'Detalii serviciu',
 'process'=>[
  ['title'=>'Înregistrare','text'=>'Notăm modelul, accesoriile și problema semnalată.'],['title'=>'Diagnosticare','text'=>'Verificăm mecanica, alimentarea, imprimarea și scanarea.'],['title'=>'Confirmare','text'=>'Comunicăm soluția, costul și termenul înainte de lucrare.'],['title'=>'Reparație','text'=>'Reparăm sau înlocuim componentele defecte.'],['title'=>'Testare','text'=>'Testăm copierea, scanarea și imprimarea în mai multe regimuri.'],['title'=>'Predare','text'=>'Predăm echipamentul și documentele lucrării.'],
 ],
 'cta_eyebrow'=>'Copiatorul nu funcționează corect?','cta_title'=>'Descrie-ne problema sau adu echipamentul la diagnosticare.','contacts'=>'Contacte și adresă','detail_eyebrow'=>'Service MFD și copiatoare','consultation'=>'Solicită o consultație','diagnostic_title'=>'Diagnosticare înainte de reparație','diagnostic_note'=>'Identificăm cauza exactă și evităm înlocuirea inutilă a pieselor.','time_note'=>'Termenul final depinde de model și disponibilitatea pieselor.','description_title'=>'Despre acest serviciu','symptoms_eyebrow'=>'Când este necesară intervenția','symptoms_title'=>'Semne frecvente','steps_eyebrow'=>'Cum lucrăm','steps_title'=>'Etapele serviciului','price_title'=>'Prețul se stabilește după diagnosticare','price_text'=>'Costul depinde de model, defect, volumul lucrării și piesele necesare. Confirmăm prețul înainte de reparație.','other_services'=>'Alte servicii MFD și copiatoare','all_services'=>'Toate serviciile MFD',
 'services'=>[
  'diagnosticare-mfd'=>['title'=>'Diagnosticare MFD și copiatoare','short'=>'Verificarea completă a funcțiilor de copiere, imprimare, scanare și alimentare.','intro'=>'Identificăm cauza defectului și prezentăm soluția recomandată înainte de reparație.','description'=>'Testăm modulele mecanice și electronice, citim codurile de eroare și verificăm aparatul în regimurile în care apare problema.','time'=>'De regulă: 1–2 zile','symptoms'=>['Apare un cod de eroare','Aparatul nu pornește','Copierea sau scanarea se blochează','Defectul apare intermitent'],'steps'=>['Înregistrăm simptomele','Testăm modulele relevante','Prezentăm concluzia și oferta']],
  'reparatie-alimentare'=>['title'=>'Reparația sursei și electronicii','short'=>'Remedierea problemelor de pornire, alimentare și plăci electronice.','intro'=>'Diagnosticăm sursa, controlerele și circuitele atunci când echipamentul nu pornește sau se restartează.','description'=>'Măsurăm tensiunile, verificăm protecțiile și componentele electronice, apoi testăm stabilitatea aparatului după intervenție.','time'=>'De regulă: 2–5 zile','symptoms'=>['Echipamentul nu pornește','Se oprește în timpul lucrului','Se restartează repetat','Afișajul rămâne blocat'],'steps'=>['Verificăm alimentarea','Localizăm circuitul defect','Reparăm și testăm stabilitatea']],
  'reparatie-mecanism-hartie'=>['title'=>'Reparația mecanismului de hârtie','short'=>'Eliminarea blocajelor și repararea rolelor, tăvilor și mecanismelor de transport.','intro'=>'Reparăm alimentarea și transportul hârtiei pentru copiere și imprimare fără blocaje.','description'=>'Inspectăm rolele, senzorii, separatoarele, angrenajele și traseul hârtiei, curățând sau înlocuind componentele uzate.','time'=>'De regulă: 1–3 zile','symptoms'=>['Hârtia se blochează frecvent','Aparatul ia mai multe foi','Nu preia hârtia din tavă','Foile ies îndoite sau rupte'],'steps'=>['Verificăm traseul hârtiei','Curățăm și măsurăm uzura','Înlocuim piesele și testăm']],
  'reparatie-calitate-imprimare'=>['title'=>'Remedierea calității imprimării','short'=>'Soluții pentru dungi, pete, fundal gri, imprimare palidă sau neuniformă.','intro'=>'Restabilim calitatea copierii și imprimării prin diagnosticarea ansamblurilor de imagine și fixare.','description'=>'Verificăm cartușul, unitatea de imagine, transferul, cuptorul și calibrarea pentru a identifica precis cauza defectului.','time'=>'De regulă: 1–3 zile','symptoms'=>['Dungi sau pete pe pagină','Imagine palidă ori neuniformă','Tonerul nu se fixează','Copiile au fundal gri'],'steps'=>['Analizăm pagina de test','Verificăm modulele de imagine','Reparăm și calibrăm']],
  'reparatie-scaner'=>['title'=>'Reparația scanerului și ADF','short'=>'Repararea scanării, alimentatorului automat și defectelor de copiere.','intro'=>'Diagnosticăm scanerul și alimentatorul automat de documente când copiile sunt deformate sau documentele nu sunt preluate.','description'=>'Curățăm și verificăm optica, motorul, cablurile, senzorii și rolele ADF, apoi testăm documente simple și duplex.','time'=>'De regulă: 1–4 zile','symptoms'=>['Scanarea are dungi','ADF-ul blochează documentele','Copiile sunt deformate','Scanerul face zgomote neobișnuite'],'steps'=>['Verificăm optica și ADF-ul','Curățăm sau înlocuim componente','Calibrăm și testăm']],
  'intretinere-preventiva'=>['title'=>'Întreținere și curățare preventivă','short'=>'Curățare tehnică, verificarea uzurii și prevenirea defecțiunilor costisitoare.','intro'=>'Întreținerea periodică reduce blocajele, uzura și întreruperile echipamentelor intens utilizate.','description'=>'Curățăm traseul hârtiei și modulele accesibile, verificăm contoarele și consumabilele și raportăm piesele apropiate de limita de utilizare.','time'=>'De regulă: 1 zi','symptoms'=>['Echipamentul lucrează zilnic','A crescut numărul blocajelor','Se aud zgomote noi','Calitatea a scăzut treptat'],'steps'=>['Inspectăm și citim contoarele','Curățăm mecanismele','Testăm și oferim recomandări']],
 ],
];
